services:
  - type: web
    name: iphone-manager
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=iphone_import_system.production_settings
      python manage.py migrate --noinput --settings=iphone_import_system.production_settings
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 3 --timeout 120 iphone_import_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: iphone_import_system.production_settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: iphone-manager-db
          property: connectionString
    
databases:
  - name: iphone-manager-db
    databaseName: iphone_manager
    user: iphone_manager_user
    region: oregon
    plan: free
