# Generated by Django 5.0 on 2025-09-02 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacao',
            name='frete_py_por_kg',
        ),
        migrations.RemoveField(
            model_name='importacao',
            name='peso_kg',
        ),
        migrations.AddField(
            model_name='importacao',
            name='frete_py_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Frete Paraguay em USD', max_digits=10),
        ),
    ]
