# Generated by Django 5.0 on 2025-09-02 15:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_peso_kg_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacao',
            name='frete_py_usd',
        ),
        migrations.AddField(
            model_name='importacao',
            name='frete_py_usd_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Frete PY (USD/kg)', max_digits=10),
        ),
        migrations.AddField(
            model_name='importacao',
            name='kg_py_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='KG PY ($)', max_digits=10),
        ),
    ]
